#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02

apt-get -y update
apt-get -y install haproxy

echo "
frontend tubosundayo.tech-frontend
        bind *:80
        mode http
        default_backend tubosundayo.tech-backend
backend tubosundayo.tech-backend
        balance roundrobin
        server 297923 web-01 54.210.195.223:80 check
        server 297923 web-02 52.3.248.68:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
