#!/bin/bash

# Define the SSH private key file, remote user, and remote server address
private_key="~/.ssh/school"
remote_user="ubuntu"
remote_server="100.26.243.165"

ssh -i "$private_key" "$remote_user@$remote_server"

